# Generated by Django 5.2.5 on 2025-08-07 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='bugs_report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bug_title', models.CharField(max_length=100)),
                ('bug_description', models.TextField()),
                ('status', models.CharField(choices=[('cleared', 'Cleared'), ('ongoing', 'ongoing'), ('remained', 'Remained')], default='ongoing', max_length=10)),
            ],
        ),
    ]
